commonfields:
  id: PDFUnlocker
  version: -1
name: PDFUnlocker
script: >
  register_module_line('PDFUnlocker', 'start', __line__())

  demisto.debug('pack name = Common Scripts, pack version = 1.19.29')



  from pikepdf import Pdf, PasswordError



  def unlock_pdf(args: dict):
      res = demisto.getFilePath(args.get('entryID'))
      origin_path = res['path']
      output_name = "UNLOCKED_" + res['name']

      try:
          with Pdf.open(origin_path, password=str(args.get("password"))) as unlocked_pdf:
              unlocked_pdf.save(output_name)
          return_results(file_result_existing_file(output_name))
      except PasswordError:
          return_error("Incorrect password. Please provide the correct password.")


  def main():
      args = demisto.args()
      unlock_pdf(args)


  if __name__ in ('__main__', '__builtin__', 'builtins'):
      main()

  register_module_line('PDFUnlocker', 'end', __line__())
type: python
subtype: python3
tags: []
comment: Removing the password protection from a PDF file and adding a new file entry with the unlocked PDF.
enabled: true
args:
- name: entryID
  required: true
  default: true
  description: Entry ID with PDF file.
- name: password
  required: true
  secret: true
  description: Password of PDF file.
scripttarget: 0
dockerimage: demisto/readpdf:1.0.0.2034953
fromversion: 5.0.0
tests:
- PDFUnlocker-Test
nativeimage:
- '8.8'
- '8.6'
